- components/layouts/Sidebar.tsx
- pages/api/logout.ts
- pages/login.tsx
- styles/components/Layouts.module.css
- utils/useUser.ts
> feat: logout

- components/rdv/AddRdvModal.tsx
- interfaces/json/rdv.ts
- pages/index.tsx
- pages/mes-jeunes/index.tsx
> fix: (us-28) Corrige la durée d'un rdv

- referentiel/rdv.ts
maj du wording pour les modalités d'un rdv pour s'adapter à l'affichage mobile. 
( Retour commentaire PO du ticket n 35 )
> fix: maj du wording de modalite de rdv pour le mobile

- interfaces/action.ts
- interfaces/json/action.ts
- pages/actions/index.tsx
Maj du status des actions au niveau de la route /actions
> fix: maj des status actions

- components/jeune/AddJeuneModal.tsx
- pages/mes-jeunes/index.tsx
Lors de l'ajout du jeune, on set les jeunes avec useState de React avec le nouveau jeune envoyé par le back. ( au lieu de faire un appel au login)
> fix: de la regression lors de l'ajout du jeune

- pages/actions/jeunes/[jeune_id]/[action_id]/index.tsx
- pages/actions/jeunes/[jeune_id]/index.tsx
on peut tester fonctionnellement sur :
https://pa-front-staging-pr59.osc-fr1.scalingo.io/
**TODO**
**DOING**
**DONE non testée fonctionnellement**
**DONE Testée**
> feat(node): modifs sur le web pour s'adapter au reboot node du back

- components/rdv/AddRdvModal.tsx
hotfix: correction de l ajout des rdv en fonction de l'id conseiller
> hotfix: correction de l ajout des rdv en fonction de l'id conseiller

- components/rdv/AddRdvModal.tsx
fix: correction de l ajout des rdv en fonction de id conseiller
> fix: correction de l ajout des rdv en fonction de id conseiller

- components/jeune/ListeRdvJeune.tsx
- fixtures/rendez-vous.ts
- pages/mes-jeunes/[jeune_id]/index.tsx
- tailwind.config.js
- tests/components/ListeRdvJeune.test.tsx
- tests/utils/date.test.ts
fix de l'espacement
fix de l'ordre d'apparition des rdvs, tri par le plus proche dans le temps au plus lointain
fix "min" ajoutés à l'heure du rdv
> fix: Retours recette correction css, affichage rdvs

- components/AppHead.tsx
- components/layouts/Layout.tsx
- pages/index.tsx
- pages/mes-jeunes/[jeune_id]/actions/[action_id]/index.tsx
- pages/mes-jeunes/[jeune_id]/actions/index.tsx
- pages/mes-jeunes/[jeune_id]/index.tsx
- pages/mes-jeunes/index.tsx
A date, toutes nos pages ont le même `<title>`
Pour rendre nos pages plus accessibles, on doit rendre ce contenu dynamique pour permettre d'identifier les changements de page et comprendre la progression.
> fix: Ajoute title accessible aux pages

- pages/login.tsx
> [US-259] connexion auto conseiller similo et pe

- components/jeune/InputRechercheDossier.tsx
- pages/mes-jeunes/index.tsx
- tests/pages/MesJeunes.page.test.tsx
> fix: modale de creation jeune lorsque conseiller n est pas MILO

- @types/next-auth.d.ts
- pages/api/auth/[...nextauth].ts
- utils/auth/authenticator.ts
- utils/fetchJson.ts
- utils/withMandatorySessionOrRedirect.ts
fix: faire un logout lorsque le refresh token a expiré
> fix: logout when refresh token is expired

- components/jeune/DetailsJeune.tsx
- components/jeune/SuccessAddJeuneMilo.tsx
- fixtures/jeune.ts
- interfaces/jeune.ts
- styles/typography.css
- tests/components/DetailsJeune.test.tsx
- tests/pages/MiloCreationJeune.page.test.tsx
Afficher la pastille du statut jeune non activé dans le détail
> feat: (us-155) status jeune

- components/jeune/FormulaireJeunePoleEmploi.tsx
- components/jeune/FormulaireRechercheDossier.tsx
- tests/pages/MiloCreationJeune.page.test.tsx
- tests/pages/PoleEmploiCreationJeune.page.test.tsx
Amélioration accessibilité des messages d'erreur des formulaires d'ajout de jeune MILO et Pôle Emploi 
cf. https://zeroheight.com/2f9442f46/p/37d8c8-text/t/15c149
> fix: Amélioration wording formulaire erreur

- .github/workflows/github-actions.yml
- components/jeune/DetailsJeune.tsx
- fixtures/jeune.ts
- interfaces/jeune.ts
- tests/components/DetailsJeune.test.tsx
feat: ajout de la date de creation sur la fiche jeune
> feat: ajout de la date de creation sur la fiche jeune

- components/jeune/DetailsJeune.tsx
- pages/mes-jeunes/index.tsx
- tests/components/DetailsJeune.test.tsx
feat: supprimer identifiant jeune dans liste et détail
bonus: align items center dans liste des jeunes (le chevron n'était pas aligné verticalement)
> feat: supprimer identifiant jeune dans liste et detail

- utils/isEmailValid.ts
Try to fix https://sonarcloud.io/organizations/socialgouv/rules?open=typescript%3AS5852&rule_key=typescript%3AS5852
> fix: try preventing ReDOS by limiting email regex size

- tests/components/DetailsJeune.test.tsx
- utils/analytics/matomo.ts
- utils/analytics/useMatomo.tsx
feat: ajout des custom dimensions 
- dimension 1 = conseiller
- dimension 2 = structure du conseiller en cours (qu'on récupère de la session)
us 332
> feat: ajout des custom dimensions 1&2

- components/action/FiltresActions.tsx
- components/ui/Button.tsx
- pages/mes-jeunes/[jeune_id]/actions/index.tsx
- pages/mes-jeunes/[jeune_id]/index.tsx
- styles/components/Button.module.css
- tests/components/RechercheJeune.test.tsx
- tests/pages/ActionsJeune.page.test.tsx
feat: Ajout des onglets/filtres sur la liste des actions d'un jeune. 
Pour l'a11y, je me suis basée sur [l'exemple de accede web](https://www.accede-web.com/notices/interface-riche/onglets/)
> feat(us-318): filtre liste actions jeune

- jest.config.js
- pages/index.tsx
- pages/login.tsx
- pages/mes-jeunes/index.tsx
- setupTests.js
- tests/pages/Login.page.test.tsx
feat: remontée dans matomo lors du click sur le lien depuis le mail du conseiller. 
Il faut que le lien dans le mail renvoie vers la bonne url avec le bo query 'source'
> feat: ajout de matomo dans login et gestion du query mail

- components/jeune/AjouterJeuneButton.tsx
- pages/mes-jeunes/index.tsx
- pages/mes-jeunes/milo/creation-jeune.tsx
- pages/mes-jeunes/pole-emploi/creation-jeune.tsx
- tests/pages/MiloCreationJeune.page.test.tsx
- tests/pages/PoleEmploiCreationJeune.page.test.tsx
feat: Ajouter le bouton 'Ajouter Jeune' après le succès de la création
bonus refactorisation du boutton 'Ajouter jeune' dans un composant
> feat: (us-381) ajouter le bouton d'ajout jeune après création

- components/layouts/Conversation.tsx
Corrige nombre erronés de messages non lus, certains apparaissant lus dans le chat, mais en non lus dans le tableau.
> fix: Corrige conditions messages non lus

- components/jeune/TableauJeunes.tsx
- fixtures/jeune.ts
- interfaces/action.ts
- interfaces/jeune.ts
- pages/mes-jeunes/index.tsx
- services/actions.service.ts
- tailwind.config.js
- tests/pages/Action.page.test.tsx
- tests/pages/MesJeunes.page.test.tsx
feat: Ajout d'une nouvelle colonne dans le tableau des jeunes pour afficher le nombre d'actions non terminées par jeune.
> feat: (us-376) nb actions non terminees jeunes

- components/Modal.tsx
- components/RenseignementAgenceModal.tsx
- components/RequiredValue.tsx
- components/jeune/FormulaireJeunePoleEmploi.tsx
- components/jeune/RechercheJeune.tsx
- components/rdv/EditionRdvForm.tsx
- components/ui/ResettableTextInput.tsx
- components/ui/SelectAutocomplete.tsx
- pages/index.tsx
- pages/supervision/index.tsx
- services/conseiller.service.ts
- stories/components/ResettableTextInput.stories.tsx
- tests/pages/Home.page.test.tsx
- tests/services/conseiller.service.test.ts
> feat: permet ajout agence libre

- components/SuccessMessage.tsx
- components/jeune/JeunesMultiselectAutocomplete.tsx
- components/rdv/EditionRdvForm.tsx
- pages/mes-jeunes/envoi-message-groupe.tsx
- tests/pages/EditionRdv.page.test.tsx
> feat: modifie destinataires rdv

- components/Conversation.tsx
- components/FilAriane.tsx
- components/jeune/DossierJeuneMilo.tsx
- components/jeune/FormulaireJeunePoleEmploi.tsx
- components/jeune/IndicationRechercheDossier.tsx
- components/jeune/IntegrationPoleEmploi.tsx
- components/jeune/JeunesMultiselectAutocomplete.tsx
- components/jeune/SuccessAddJeuneMilo.tsx
- components/jeune/SuccessAddJeunePoleEmploi.tsx
- components/layouts/ChatRoom.tsx
- components/layouts/Header.tsx
- components/rdv/EditionRdvForm.tsx
- components/ui/DeprecatedErrorMessage.tsx
- components/ui/ExternalLink.tsx
- components/ui/RdvTypeTag.tsx
- components/ui/ResettableTextInput.tsx
- pages/mes-jeunes/[jeune_id]/actions/nouvelle-action.tsx
- pages/mes-jeunes/[jeune_id]/index.tsx
- pages/mes-jeunes/[jeune_id]/suppression.tsx
- pages/mes-jeunes/envoi-message-groupe.tsx
- pages/profil.tsx
- pages/supervision/index.tsx
- styles/components/Layouts.module.css
- styles/globals.css
- styles/typography.css
- tailwind.config.js
le plus gros est fait côté typo, en scout rule je dois encore me synchro avec les designers.
> chore: Refonte partie 2

- components/rdv/EditionRdvForm.tsx
> ajoute "qui" dans éditorial rdv

- components/ui/ResettableTextInput.tsx
- pages/reaffectation/index.tsx
- services/jeunes.service.ts
- tests/pages/Reaffectation.page.test.tsx
- tests/services/jeunes.service.test.ts
Contrairement à la maquette, ne pas prendre en compte le style, le maître mot étant de laisser au maximum le natif
> feat(US-728): Ajoute boutons radios message réaffectation

- clients/api.client.ts
- components/ui/Button.tsx
- fixtures/conseiller.ts
- fixtures/services.ts
- interfaces/conseiller.ts
- interfaces/json/conseiller.ts
- pages/mes-jeunes/index.tsx
- services/conseiller.service.ts
- tests/components/RechercheJeune.test.tsx
- tests/pages/MesJeunes.page.test.tsx
- tests/renderPage.tsx
- tests/services/conseiller.service.test.ts
> feat(US-732): Ajoute récupération bénéficiaires

- components/action/ActionRow.tsx
- components/action/TableauActionsJeune.tsx
- components/ui/IconComponent.tsx
- fixtures/action.ts
- interfaces/action.ts
- interfaces/json/action.ts
- pages/mes-jeunes/[jeune_id]/actions/[action_id].tsx
- pages/mes-jeunes/[jeune_id]/actions/nouvelle-action.tsx
- services/actions.service.ts
- tests/components/ActionRow.test.tsx
- tests/pages/Action.page.test.tsx
- tests/pages/NouvelleAction.page.test.tsx
- tests/services/actions.service.test.ts
> feat: ajouter et afficher action dateEcheance

- components/Menu.tsx
- components/MenuLinks.tsx
- components/chat/ChatRoom.tsx
- components/layouts/AlertDisplayer.tsx
- components/layouts/Sidebar.tsx
- components/ui/MenuLink.tsx
- pages/mes-jeunes/[jeune_id]/actions/[action_id].tsx
- pages/reaffectation.tsx
- referentiel/queryParam.ts
> fix: Améliorations accessibilité menu mobile et refacto QueryParams Alerts

- components/jeune/DeleteJeuneActifModal.tsx
- components/rdv/EditionRdvForm.tsx
- components/ui/Form/Select.tsx
- pages/mes-jeunes/[jeune_id]/actions/nouvelle-action.tsx
- stories/components/Select.stories.tsx
> chore: ajoute composant Select

- components/MenuLinks.tsx
- components/NouveautesMenuButton.tsx
- components/layouts/Sidebar.tsx
- setupTests.js
- utils/useLeanBeWidget.ts
un lien Nouveautés est apparu dans la sidebar
> poc lean be

- components/action/RadioButton.tsx
- components/action/RadioButtonStatus.tsx
- components/action/StatutActionForm.tsx
- fixtures/action.ts
- interfaces/action.ts
- interfaces/json/action.ts
- pages/mes-jeunes/[jeune_id]/actions/[action_id].tsx
- stories/components/RadioButton.stories.tsx
- tests/pages/Action.page.test.tsx
Statut est disabled quand action terminée et qualifiée
Action ne peut pas être supprimée si commentaire ou si terminée et qualifiée
> feat(US-953):  Bloque changement statut action qualifiée et suppression action qualifiée ou avec commentaire

- components/action/ActionRow.tsx
- components/action/TableauActionsJeune.tsx
- components/jeune/TableauJeunes.tsx
- components/rdv/RdvRow.tsx
- components/rdv/TableauRdv.tsx
- components/ui/Table/HeaderCell.tsx
- components/ui/Table/RowCell.tsx
- interfaces/rdv.ts
- pages/mes-rendezvous.tsx
- presentation/MesRdvViewModel.ts
- tests/presentation/MesRdvViewModel.test.ts
> fix: remet date rdv fiche jeune

- components/jeune/BlocFavoris.tsx
- components/jeune/BlocSituation.tsx
- components/jeune/DetailsJeune.tsx
- pages/mes-jeunes/[jeune_id].tsx
- tests/components/DetailsJeune.test.tsx
- tests/pages/FicheJeune.page.test.tsx
Lien (chelou) vers le [Notion](https://www.notion.so/fabnummas/User-Story-63f794971ff1475990946aafe51f4181?p=443cc52712054286a97612eab2dea3cb&pm=s)
> feat(983): Indicateurs chiffrés conseiller - Refonte fiche jeune - bloc favoris

- components/action/RadioButton.tsx
- pages/mes-jeunes/[jeune_id]/actions/[action_id].tsx
-correction du comportement sur l'affichage du bouton supprimer : ne plus pouvoir supprimer si statut === Terminee
-correction du comportement sur le changement de statut : on ne peut plus modifier le statut quand il est en Terminee , sauf quand s'est une action MILO qui n'est pas encore qualifié
> feat:  correction de l’affichage du bouton supprimer

- fixtures/listes-de-diffusion.ts
- fixtures/services.ts
- interfaces/liste-de-diffusion.ts
- pages/mes-jeunes/envoi-message-groupe.tsx
- pages/mes-jeunes/listes-de-diffusion.tsx
- services/listes-de-diffusion.service.ts
- tests/pages/EnvoiMessageGroupe.page.test.tsx
- tests/pages/ListesDiffusion.page.test.tsx
- tests/renderWithContexts.tsx
- tests/services/listes-de-diffusion.service.test.ts
- tests/utils/withMandatorySessionOrRedirect.test.ts
- utils/injectionDependances/container.ts
- utils/route-labels.ts
> feat(us-1228): page mes listes de diffusion

- components/layouts/AlerteDisplayer.tsx
- components/ui/Button/Button.tsx
- fixtures/services.ts
- pages/mes-jeunes/listes-de-diffusion.tsx
- pages/mes-jeunes/listes-de-diffusion/edition-liste.tsx
- referentiel/alerteParam.ts
- services/listes-de-diffusion.service.ts
- tests/components/AlerteDisplayer.test.tsx
- tests/pages/EditionListeDiffusion.page.test.tsx
- tests/pages/ListesDiffusion.page.test.tsx
- tests/services/listes-de-diffusion.service.test.ts
> feat(US-1224): Ajoute formulaire création liste de diffusion

- components/jeune/BeneficiaireIndications.tsx
- components/layouts/AlerteDisplayer.tsx
- fixtures/services.ts
- pages/mes-jeunes/edition-rdv.tsx
- pages/mes-jeunes/listes-de-diffusion.tsx
- pages/mes-jeunes/listes-de-diffusion/edition-liste.tsx
- referentiel/alerteParam.ts
- services/listes-de-diffusion.service.ts
- tests/components/AlerteDisplayer.test.tsx
- tests/pages/EditionListeDiffusion.page.test.tsx
- tests/pages/EditionRdv.page.test.tsx
- tests/pages/ListesDiffusion.page.test.tsx
- tests/services/listes-de-diffusion.service.test.ts
> feat(US-1225): Ajoute modification liste de diffusion

- components/jeune/BeneficiairesMultiselectAutocomplete.tsx
- components/rdv/EditionRdvForm.tsx
- components/ui/Form/Input.tsx
- components/ui/Form/InputError.tsx
- components/ui/Form/SelectAutocomplete.tsx
- interfaces/evenement.ts
- interfaces/json/evenement.ts
- pages/mes-jeunes/edition-rdv.tsx
- pages/mes-jeunes/envoi-message-groupe.tsx
- pages/mes-jeunes/listes-de-diffusion/edition-liste.tsx
- pages/offres/[offre_type]/[offre_id]/partage.tsx
- pages/offres/partage-recherche.tsx
- services/evenements.service.ts
- tests/components/BeneficiairesMultiselectAutocomplete.test.tsx
- tests/pages/EditionRdv.page.test.tsx
- tests/services/evenements.service.test.ts
> feat-1296 : nombre maximal de participants à une AC

- pages/mes-jeunes/[jeune_id]/actions/[action_id]/qualification.tsx
- services/actions.service.ts
- tests/pages/Qualification.page.test.tsx
- tests/services/actions.service.test.ts
En attente activation des commentaires par i-Milo pour mettre en prod la feature concernant le formulaire de qualification d'une action en SNP
cf. https://mattermost.incubateur.net/spie/pl/q9hyzu94ffn4uefriasn518ezh
> feat(US-1414): revert commentaire titre snp

- clients/firebase.client.ts
- components/chat/Conversation.tsx
- components/chat/DetailMessageListeDeDiffusion.tsx
- components/chat/DisplayMessageListeDeDiffusion.tsx
- components/chat/HeaderChat.tsx
- components/chat/ListeListesDeDiffusion.tsx
- components/chat/MessagesListeDeDiffusion.tsx
- components/chat/RubriqueListesDeDiffusion.tsx
- fixtures/message.ts
- fixtures/services.ts
- interfaces/message.ts
- services/jeunes.service.ts
- tests/components/DetailMessageListeDeDiffusion.test.tsx
- tests/components/MessagesListeDeDiffusion.test.tsx
- tests/services/jeunes.service.test.ts
- utils/date.ts
> feat: afficher destinataires message liste de diffusion

- components/chat/ConversationTile.tsx
> feat(US-1460): badge message non lu bénéficiaire

- components/chat/Conversation.tsx
- components/chat/DisplayMessage.tsx
- tests/components/DisplayMessage.test.tsx
> feat(us-1320): messagerie bulle

- pages/mes-jeunes/[jeune_id].tsx
- pages/mes-jeunes/[jeune_id]/actions/[action_id].tsx
- pages/mes-jeunes/[jeune_id]/favoris.tsx
- pages/mes-jeunes/[jeune_id]/historique.tsx
- pages/mes-jeunes/[jeune_id]/indicateurs.tsx
- pages/mes-jeunes/[jeune_id]/rendez-vous-passes.tsx
- pages/mes-jeunes/edition-rdv.tsx
- tests/pages/Action.page.test.tsx
- tests/pages/Favoris.page.test.tsx
- tests/pages/Historique.page.test.tsx
- tests/pages/Indicateurs.page.test.tsx
- tests/pages/RendezvousPasses.page.test.tsx
- utils/analytics/matomo.ts
> feat(us-1488): tracking-multi-utilisateurs-nom-des-pages

- next.config.js
- package.json
- pages/login.tsx
- pages/mes-jeunes/edition-rdv.tsx
- pages/mes-jeunes/envoi-message-groupe.tsx
- pages/offres/[offre_type]/[offre_id]/partage.tsx
- tests/pages/EnvoiMessageGroupe.page.test.tsx
- tests/pages/Login.page.test.tsx
- tests/pages/PartageOffre.page.test.tsx
- tests/pages/edition-rdv/EditionRdv.page.test.tsx
https://trello.com/c/OFpcwt8O/1538-404-sur-les-redirection-vers-la-page-index
> fix: fix 404 on index page

- components/ui/Form/Select.tsx
- pages/mes-jeunes/[jeune_id]/actions/nouvelle-action.tsx
- tests/pages/NouvelleAction.page.test.tsx
> feat(us-1552): ux writing action milo

- components/chat/ChatRoom.tsx
- components/chat/ConversationTile.tsx
- styles/components/Layouts.module.css
> feat(us-1567) : lama-messagerie-liste-messages

- components/ConfirmationDeleteConseillerModal.tsx
- components/ConfirmationSuppressionCompteConseillerModal.tsx
- components/Modal.tsx
- fixtures/services.ts
- pages/profil.tsx
- services/conseiller.service.ts
- tests/pages/Profil.page.test.tsx
- tests/services/conseiller.service.test.ts
- utils/analytics/useMatomo.tsx
deux tickets:
cf https://www.figma.com/file/tx55Vb7kksqKScxOfUL97z/Suppression-compte-CEJ-%3E-BRSA?node-id=12-140&t=HkxWGf23GHDiIigO-0
modifications design vu avec Matthieu.
NE PAS SUPPRIMER de compte en testant
> feat(US-BRSA-101-103): Ajoute suppression conseiller pour PE

- components/ui/Form/Label.tsx
- components/ui/Table/TD.tsx
- components/ui/Table/TH.tsx
- components/ui/Table/TR.tsx
- fixtures/conseiller.ts
- interfaces/conseiller.ts
- interfaces/json/conseiller.ts
- pages/reaffectation.tsx
- services/conseiller.service.ts
- services/jeunes.service.ts
- tests/pages/Reaffectation.page.test.tsx
- tests/services/conseiller.service.test.ts
- tests/services/jeunes.service.test.ts
Se brancher sur la review-app API : https://github.com/SocialGouv/pass-emploi-api/pull/1153
> Rework reaffectation

- pages/mes-jeunes/listes-de-diffusion/edition-liste.tsx
- tests/pages/EditionListeDiffusion.page.test.tsx
- créer une liste de diffusion
- modifier une liste de diffusion
> feat(us-1915): completion formualires portail conseiller pt2

- pages/mes-jeunes/envoi-message-groupe.tsx
- pages/offres/[offre_type]/[offre_id]/partage.tsx
- pages/offres/partage-recherche.tsx
- tests/pages/EnvoiMessageGroupe.page.test.tsx
- tests/pages/PartageOffre.page.test.tsx
- tests/pages/PartageRecherche.page.test.tsx
- Formulaire partage de critères de recherches 
- Partager une offre 
- Message multi destinataire
> feat(us-1936): completion formulaires portail conseiller pt3

- components/RenseignementAgenceForm.tsx
- components/RenseignementAgenceMissionLocaleForm.tsx
- components/RenseignementAgenceModal.tsx
- components/jeune/DeleteJeuneActifModal.tsx
- Modale confirmation suppression d’un bénéficiaire 
- Ajout de structure conseiller  
- Désinscrire un bénéficiaire d’une session milo -> supprimer un bénéficiaire actif (je l'ai modifié dans le ticket trello aussi)
> feat(us-1915): completion formulaires portail conseiller pt4

- app/autherror/AuthErrorPage.tsx
- app/autherror/page.tsx
(cherry picked from commit ce2501fe65a328a973fb1c4f92977a6fe0845699)
> feat: prepare page /autherror

- components/HeaderCGUConseillerCEJ.tsx
- components/HeaderCGUConseillerPassEmploi.tsx
Changement de la date des CGU CEJ et pass emploi
> Modification date des cgu
